/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eleqstory_db;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.PreparedStatement;
import java.io.FileInputStream;
import java.io.InputStream;

/**
 *
 * @author danil
 */
public class Main_Window extends javax.swing.JFrame {
    
    public String imgPath = null;

    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        initComponents();
    }
    
    /*** the own code. ***/
    
    public Connection getConnection() {
        /*** gets the connection with the database. ***/
        
        // declare the Connection variable and initialize it to null.
        Connection con = null;
        
        try {
            // get the connection with the local database.
            con = DriverManager.getConnection("jdbc:mysql://localhost/products_db2", "root", "");
            // return the status of the connection as a result.
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
            // show the other window with the "Not connected" label if there was no connection.
            JOptionPane.showMessageDialog(null, "Not connected!", "Something has gone wrond!", HEIGHT);
            // return the null value as a result if fail.
            return null;
        }
    }
    
    public ImageIcon resizeImg(String imagePath, byte[] pic) {
        /*** gets an image using its path and resizes it for the lbl_image label. ***/
        
        // declare the variable that will conteins the original image. But now it's null.
        ImageIcon myImage = null;
        
        // check if we have the path we could get the image with.
        if (imagePath != null) {
            // if so, get the image using the path.
            myImage = new ImageIcon(imagePath);
        }
        else {
            myImage = new ImageIcon(pic);
        }
        
        // resize the image to the lbl_image label size using an instance of the Image class.
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        
        // get the new scaled image and store it as an icon.
        ImageIcon image = new ImageIcon(img2);
        
        return image;
    }
    
    public boolean checkInputs() {
        /*** checks if the all fields aren't empty. ***/
        
        if (txt_name.getText() == null || txt_price.getText() == null || txt_addDate.getText() == null) {
            return false;
        }
        else {
            try {
                // try to convert the price to a float value and return true if success.
                Float.parseFloat(txt_price.getText());
                return true;
            }
            catch (Exception ex) {
                return false;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_addDate = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Insert = new javax.swing.JButton();
        btn_ChooseImage = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("ID:");

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Price:");

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Add Date:");

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Image:");

        txt_id.setBackground(java.awt.Color.white);
        txt_id.setOpaque(false);
        txt_id.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_name.setOpaque(false);
        txt_name.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_price.setOpaque(false);
        txt_price.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_addDate.setText("yyyy/MM/dd");
        txt_addDate.setOpaque(false);
        txt_addDate.setPreferredSize(new java.awt.Dimension(15, 50));

        lbl_image.setBackground(new java.awt.Color(230, 230, 230));
        lbl_image.setForeground(new java.awt.Color(1, 1, 1));
        lbl_image.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Add Date"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        btn_Insert.setBackground(new java.awt.Color(193, 193, 193));
        btn_Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/add-smaller.png"))); // NOI18N
        btn_Insert.setText("Insert");
        btn_Insert.setIconTextGap(10);
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });

        btn_ChooseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/download-smaller.png"))); // NOI18N
        btn_ChooseImage.setText("Choose Image");
        btn_ChooseImage.setIconTextGap(10);
        btn_ChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChooseImageActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(193, 193, 193));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/reload-smaller.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.setIconTextGap(10);

        jButton4.setBackground(new java.awt.Color(193, 193, 193));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/criss-cross-smaller.png"))); // NOI18N
        jButton4.setText("Remove");
        jButton4.setIconTextGap(10);

        jButton5.setBackground(new java.awt.Color(193, 193, 193));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/left-arrow.png"))); // NOI18N
        jButton5.setText("First");
        jButton5.setIconTextGap(10);

        jButton6.setBackground(new java.awt.Color(193, 193, 193));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/previous.png"))); // NOI18N
        jButton6.setText("Previous");
        jButton6.setIconTextGap(7);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(193, 193, 193));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/next.png"))); // NOI18N
        jButton7.setText("Next");
        jButton7.setIconTextGap(7);
        jButton7.setMaximumSize(new java.awt.Dimension(104, 38));
        jButton7.setMinimumSize(new java.awt.Dimension(104, 38));

        jButton8.setBackground(new java.awt.Color(193, 193, 193));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/right-arrow.png"))); // NOI18N
        jButton8.setText("Last");
        jButton8.setIconTextGap(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ChooseImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Insert)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChooseImageActionPerformed
        /*** allows to choose an image using the file chooser and sets the image as an icon into the lbl_image label. ***/
        
        // set the primordial directory as user/home.
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // allow to use the jpg and png formats only.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        
        // get the result of the user has chosen an image.
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            // if so, get the selected file.
            File selectedFile = file.getSelectedFile();
            // get the absolute path of the selected file.
            String path = imgPath = selectedFile.getAbsolutePath();
            // set the image as an icon of the lbl_image.label.
            lbl_image.setIcon(resizeImg(path, null));;
        }
        // if the user has not chosen an image.
        else {
            // then we just print the message that says "No File Selected".
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btn_ChooseImageActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.out.println("btn_Previous");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        /*** processes a query for data sending. ***/
        
        if (checkInputs() && imgPath != null) {
            try {
                Connection con = getConnection();
                
                String query = "INSERT INTO products (name, price, add_date, image) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(query);
                
                // set the name.
                ps.setString(1, txt_name.getText());
                // set the price.
                ps.setString(2, txt_price.getText());
                // set the added date.
                ps.setString(3, txt_addDate.getText());
                
                // get a stream of the image and set it into the database.
                InputStream img = new FileInputStream(new File(imgPath));
                ps.setBlob(4, img);
                
                // execute the query.
                ps.executeUpdate();
                
                // show a success message.
                JOptionPane.showMessageDialog(null, "The data has been successfully added!");
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
        }
    }//GEN-LAST:event_btn_InsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChooseImage;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_addDate;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
